name: Required Actions Demo
on: [push]
jobs:
  job-one:
    strategy:
      matrix:
        version: [1, 2]
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello, this job one. it will pass"
      - run: exit 1
  job-two:
    runs-on: ubuntu-latest
    needs: job-one
    if: always()
    steps:
      - name: job1 did not succeed
        if: needs.job-one.result != 'success'
        run: core.setFailed("job 1 did not succeeded")
      - name: job 1 did succeed
        run: |
          echo "job 1 finished successfully"
          exit 0
