name: Required Actions Demo
on: [push]
jobs:
  job-one:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello, this job one. it will fail"
      - run: exit 1
  job-two:
    runs-on: ubuntu-latest
    needs: job-one
    steps:
      - run: echo "Hello, this job two with status ${{ job.status }}."
