name: Required Actions Demo
on: [push]
jobs:
  job-one:
    strategy:
      matrix:
        version: [10, 12, 14]
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello, this job one. it will pass"
      - run: exit 0
  job-two:
    runs-on: ubuntu-latest
    needs: job-one
    steps:
      - run: echo "Hello, this job two with status ${{ job.status }}."
