name: Required Actions Demo
on: [push]
jobs:
  job-one:
    strategy:
      matrix:
        version: [1, 2]
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello, this job one. it will pass"
      - run: exit 0
  job-two:
    runs-on: ubuntu-latest
    needs: job-one
    if: always()
    steps:
      - run: echo "Hello, this job two with status ${{ job.status }}."
      - run: echo "job one had status ${{ needs.job-one.result }}."
      - name: job1 succeeded
        if: needs.job-one.result == 'success'
        run: |
          echo "job 1 succeeded"
          exit 0
      - run: |
          echo "job 1 did not succeed"
          exit 1
